### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Adds segment numbers next to the ID's, so it's easier to see what segment ID matches it's file, when extracting the CombinedAudio.bin in CATool.py.

### CODE REVIEW

**Comment by Cracko298** [comment]
The audio starts from an itteration of 0, making these Segment Numbers inaccurate.

Please fix, and align all Integers in the same row for easier readability, and I'll merge into main branch.

**Comment by ghost** [comment]
> The audio starts from an iteration of 0, making these Segment Numbers inaccurate.

I was able to get the bow audio at 320, with the iteration being 1.

**Comment by Cracko298** [comment]
Not all IDs are Present in the ID list.
Segments go from 0 upwards of 550.

**Comment by Cracko298** [comment]
Closing PR, because this has already been done, and is conflicting with main branch.

**Pull request closed without merging**
